// Provinsi, kabupaten/kota, and pelabuhan perikanan for the whole of Indonesia.
// Generated by scripts/build-wilayah.mjs; edit that script, not the JSON.
import provinsiData from './provinsi.json'
import kabKotaData from './kabupaten-kota.json'
import pelabuhanData from './pelabuhan.json'

export type Wilayah = {
  // Kemendagri code: "11" for a provinsi, "11.01" for a kabupaten/kota.
  kode: string
  nama: string
}

export type Pelabuhan = {
  // Unique and stable: the KKP code, or code plus name slug where KKP reuses a code ("712.35.31-panarukan").
  id: string
  // KKP code: WPP.provinsi.urutan, e.g. "571.11.01". Not unique; use id to tell ports apart.
  kode: string
  nama: string
  // PPS, PPN, PPP, PPI, PP, or CP.
  jenis: string
  // Usually one; a port on a regency border is listed under each.
  kabKota: string[]
  // From PIPP; the kabupaten/kota's centre where PIPP's point was missing or implausible (see the build script).
  lat: number | null
  lng: number | null
}

export type LatLng = { lat: number; lng: number }

export const PROVINSI: Wilayah[] = provinsiData
const KAB_KOTA: Wilayah[] = kabKotaData
const PELABUHAN: Pelabuhan[] = pelabuhanData

export function getKabupatenKota(provinsiKode: string): Wilayah[] {
  return KAB_KOTA.filter((k) => k.kode.startsWith(`${provinsiKode}.`))
}

export function getPelabuhan(kabKotaKode: string): Pelabuhan[] {
  return PELABUHAN.filter((p) => p.kabKota.includes(kabKotaKode))
}

const PELABUHAN_BY_ID = new Map(PELABUHAN.map((p) => [p.id, p]))

// Satu pelabuhan berdasarkan id-nya — dipakai saat menyimpan pilihan PPI dari form.
export function getPelabuhanById(id: string): Pelabuhan | undefined {
  return PELABUHAN_BY_ID.get(id)
}

const KAB_KOTA_NAMA = new Map(KAB_KOTA.map((k) => [k.kode, k.nama.trim()]))
const PROVINSI_NAMA = new Map(PROVINSI.map((p) => [p.kode, p.nama.trim()]))

// Case-insensitive match on the port's name. An empty query returns every port.
export function searchPelabuhan(query: string): Pelabuhan[] {
  const needle = query.trim().toLowerCase()
  return needle ? PELABUHAN.filter((p) => p.nama.toLowerCase().includes(needle)) : PELABUHAN
}

// "Kota Bitung, Sulawesi Utara", from the port's first kabupaten/kota.
export function getLokasiPelabuhan(pelabuhan: Pelabuhan): string {
  const kabKota = pelabuhan.kabKota[0]
  const provinsi = kabKota.split('.')[0]
  return [KAB_KOTA_NAMA.get(kabKota), PROVINSI_NAMA.get(provinsi)].filter(Boolean).join(', ')
}

// Names that aren't in the KKP list: the demo listings seeded before the national data was added.
const LEGACY_PPI: Record<string, LatLng> = {
  'PPI Bitung': { lat: 1.4406, lng: 125.195 },
  'PPI Tanjung Priok': { lat: -6.1045, lng: 106.8053 },
  'PPI Benoa': { lat: -8.7454, lng: 115.2116 },
  'PPI Ambon': { lat: -3.6954, lng: 128.1814 },
  'PPI Cilacap': { lat: -7.727, lng: 109.008 },
}

const PELABUHAN_BY_NAMA = new Map<string, Pelabuhan>()
for (const p of PELABUHAN) if (!PELABUHAN_BY_NAMA.has(p.nama)) PELABUHAN_BY_NAMA.set(p.nama, p)

// Where a port is, by the name stored with a listing (`catches.catch_location`, `profiles.ppi_location`).
// Null for a name that isn't a known port, such as "Belum diatur".
export function getKoordinatPelabuhan(nama: string | null | undefined): LatLng | null {
  if (!nama) return null
  const legacy = LEGACY_PPI[nama]
  if (legacy) return legacy
  const port = PELABUHAN_BY_NAMA.get(nama)
  return port && port.lat !== null && port.lng !== null ? { lat: port.lat, lng: port.lng } : null
}
