// Provinsi, kabupaten/kota, and pelabuhan perikanan for the whole of Indonesia.
// Generated by scripts/build-wilayah.mjs; edit that script, not the JSON.
import provinsiData from './provinsi.json'
import kabKotaData from './kabupaten-kota.json'
import pelabuhanData from './pelabuhan.json'

export type Wilayah = {
  // Kemendagri code: "11" for a provinsi, "11.01" for a kabupaten/kota.
  kode: string
  nama: string
}

export type Pelabuhan = {
  // KKP code: WPP.provinsi.urutan, e.g. "571.11.01".
  kode: string
  nama: string
  // PPS, PPN, PPP, PPI, PP, or CP.
  jenis: string
  // Usually one; a port on a regency border is listed under each.
  kabKota: string[]
}

export const PROVINSI: Wilayah[] = provinsiData
const KAB_KOTA: Wilayah[] = kabKotaData
const PELABUHAN: Pelabuhan[] = pelabuhanData

export function getKabupatenKota(provinsiKode: string): Wilayah[] {
  return KAB_KOTA.filter((k) => k.kode.startsWith(`${provinsiKode}.`))
}

export function getPelabuhan(kabKotaKode: string): Pelabuhan[] {
  return PELABUHAN.filter((p) => p.kabKota.includes(kabKotaKode))
}
