// Centre points of every kabupaten/kota, for distances from a buyer's registered area. Server-only by use: it's
// 15 KB the browser never needs, so keep it out of client components. Generated by scripts/build-wilayah.mjs.
import koordinatData from './kabupaten-kota-koordinat.json'
import type { LatLng } from './index'

const KOORDINAT: Record<string, number[]> = koordinatData

export function getKoordinatKabKota(kode: string | null | undefined): LatLng | null {
  const point = kode ? KOORDINAT[kode] : undefined
  return point ? { lat: point[0], lng: point[1] } : null
}
